### ISSUE TITLE
Can't go run *.jsonl

### ISSUE THREAD

**Issue by nba2023** [opencomputeproject/ocp-diag-core#645] opened 2023-07-27 02:42 UTC
My go version is 1.20.6 on WSL2.
And  run command as follows:
```
user@hostname:~/workspace/ocp-diag-core/validators/spec_validator$ go run . ./samples/pcie_test.jsonl
2023/07/27 10:39:21 The <schema> flag is mandatory
```
How do I fix this issue?

**Comment by mimir-d** [comment] 2023-08-14 18:06
well, the cli is telling you what the problem is. And the readme is wrong, which should be fixed (arguably this tool is just used internally right now)

Run with `--help`
```
> go run . ./samples/pcie_test.jsonl
2023/08/14 19:03:20 The <schema> flag is mandatory
exit status 1
```

Then run it correctly with the schema flag
```
> go run . -schema ../../json_spec/output/root.json ./samples/pcie_test.jsonl
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/diagnosis -> ../../json_spec/output/diagnosis.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/dutInfo -> ../../json_spec/output/dut_info.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/error -> ../../json_spec/output/error.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/file -> ../../json_spec/output/file.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/log -> ../../json_spec/output/log.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/measurement -> ../../json_spec/output/measurement.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/measurementSeriesElement -> ../../json_spec/output/measurement_series_element.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/measurementSeriesEnd -> ../../json_spec/output/measurement_series_end.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/measurementSeriesStart -> ../../json_spec/output/measurement_series_start.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/metadata -> ../../json_spec/output/metadata.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/output -> ../../json_spec/output/root.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/sourceLocation -> ../../json_spec/output/source_location.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/subcomponent -> ../../json_spec/output/subcomponent.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/testRunArtifact -> ../../json_spec/output/test_run_artifact.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/testRunEnd -> ../../json_spec/output/test_run_end.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/testRunStart -> ../../json_spec/output/test_run_start.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/testStatus -> ../../json_spec/output/test_status.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/testStepArtifact -> ../../json_spec/output/test_step_artifact.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/testStepEnd -> ../../json_spec/output/test_step_end.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/testStepStart -> ../../json_spec/output/test_step_start.json
2023/08/14 19:04:06 Registered ext schema https://github.com/opencomputeproject/ocp-diag-core/validator -> ../../json_spec/output/validator.json
all ok
```

**Closed as completed by mimir-d** 2023-08-14 18:06 UTC
